// Siteglade motion runtime (auto-managed — safe to leave alone).
// It powers the data-attribute animation contract:
//   data-sg-reveal="<id>"   plays once when the element scrolls into view
//   data-sg-hover="<id>"    hover/press styles (pure CSS, see sg-animations.css)
//   data-sg-loop="<id>"     subtle infinite ambient motion
//   data-sg-delay="120"     reveal delay in ms · data-sg-duration="700" duration in ms
//   data-sg-ai-label="AI-generated"  a visible AI label on an image, a video or a block
// Styles live in src/styles/sg-animations.css. Both files are re-generated by
// the platform; put custom animations elsewhere.
/* eslint-disable */
// @ts-nocheck
import { sgIntroGate, onIntroDone } from '@/components/ui/intro';

const SG_GATE = {
  active: () => sgIntroGate.active,
  onOpen: (cb: () => void) => { onIntroDone(cb); },
};

if (typeof window !== 'undefined' && typeof document !== 'undefined') {
if (!window.__sgAnimations) {
	var SG_SPLIT_MODES = {"text-blur-stagger":"letters","text-word-slide":"words","text-typewriter":"chars","card-stagger-children":"children"};
	var sgReduced = false;
	try { sgReduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches; } catch (e) {}
	var sgObserver = null;
	var sgPending = [];
	var sgGateOpen = !SG_GATE.active();
	if (!sgGateOpen) {
		var sgGateFallback = window.setTimeout(function () { sgOpenGate(); }, 8000);
		SG_GATE.onOpen(function () { window.clearTimeout(sgGateFallback); sgOpenGate(); });
	}
	function sgOpenGate() {
		if (sgGateOpen) return;
		sgGateOpen = true;
		var queue = sgPending.slice();
		sgPending.length = 0;
		queue.forEach(function (element) { sgWatch(element); });
	}
	function sgEnsureObserver() {
		if (sgObserver || typeof IntersectionObserver === 'undefined') return sgObserver;
		sgObserver = new IntersectionObserver(function (entries) {
			entries.forEach(function (entry) {
				if (!entry.isIntersecting) return;
				sgObserver.unobserve(entry.target);
				entry.target.classList.add('sg-in');
			});
		}, { rootMargin: '0px 0px -10% 0px', threshold: 0.05 });
		return sgObserver;
	}
	function sgWatch(element) {
		if (!sgGateOpen) {
			if (sgPending.indexOf(element) === -1) sgPending.push(element);
			return;
		}
		if (sgReduced || !sgEnsureObserver()) {
			element.classList.add('sg-in');
			return;
		}
		sgObserver.observe(element);
	}
	function sgUnsplit(element) {
		if (typeof element.__sgOriginalText === 'string') {
			element.textContent = element.__sgOriginalText;
			delete element.__sgOriginalText;
		}
		delete element.__sgSplitMode;
	}
	function sgSplit(element, mode) {
		if (mode === 'chars') {
			var text0 = (element.textContent || '').trim();
			if (text0.length > 0) {
				element.style.setProperty('--sg-chars', String(text0.length));
				// 1ch assumes monospace; measure the REAL single-line width so the
				// typewriter cap never clips proportional-font text (scrollWidth is
				// the full content width even while max-width clips the box).
				try {
					var width = element.scrollWidth;
					if (width > 0) element.style.setProperty('--sg-tw-width', (width + 3) + 'px');
				} catch (e) {}
			}
			return;
		}
		if (mode === 'children') {
			for (var c = 0; c < element.children.length; c += 1) {
				element.children[c].style.setProperty('--sg-i', String(c));
			}
			return;
		}
		// Re-split when the granularity changed (letters <-> words).
		if (element.__sgSplitMode && element.__sgSplitMode !== mode) sgUnsplit(element);
		if (element.__sgSplitMode === mode && element.querySelector('.sg-split')) return;
		if (element.childElementCount > 0) return;
		var text = element.textContent || '';
		if (!text.trim()) return;
		element.__sgOriginalText = text;
		element.__sgSplitMode = mode;
		var parts = mode === 'letters' ? text.split('') : text.split(/(\s+)/);
		var fragment = document.createDocumentFragment();
		var index = 0;
		parts.forEach(function (part) {
			if (!part) return;
			if (/^\s+$/.test(part)) {
				fragment.appendChild(document.createTextNode(part));
				return;
			}
			var span = document.createElement('span');
			span.className = 'sg-split';
			span.style.setProperty('--sg-i', String(index));
			span.textContent = part;
			index += 1;
			fragment.appendChild(span);
		});
		element.textContent = '';
		element.appendChild(fragment);
	}
	function sgProcess(element) {
		if (!element || element.nodeType !== 1) return;
		var revealId = element.getAttribute('data-sg-reveal');
		var signature = [revealId || '', element.getAttribute('data-sg-delay') || '', element.getAttribute('data-sg-duration') || ''].join('|');
		if (element.__sgSignature === signature && !revealId) return;
		var delay = parseInt(element.getAttribute('data-sg-delay') || '', 10);
		var duration = parseInt(element.getAttribute('data-sg-duration') || '', 10);
		if (isFinite(delay) && delay >= 0) element.style.setProperty('--sg-delay', (delay / 1000) + 's');
		else element.style.removeProperty('--sg-delay');
		if (isFinite(duration) && duration > 0) element.style.setProperty('--sg-duration', (duration / 1000) + 's');
		else element.style.removeProperty('--sg-duration');
		if (element.__sgSignature === signature) return;
		element.__sgSignature = signature;
		if (!revealId) {
			sgUnsplit(element);
			element.classList.remove('sg-in');
			if (sgObserver) sgObserver.unobserve(element);
			return;
		}
		var mode = SG_SPLIT_MODES[revealId];
		if (mode === 'letters' || mode === 'words') {
			sgSplit(element, mode);
		} else {
			sgUnsplit(element);
			if (mode) sgSplit(element, mode);
		}
		element.classList.remove('sg-in');
		sgWatch(element);
	}
	function sgReplay(element) {
		if (!element || element.nodeType !== 1) return;
		if (sgObserver) sgObserver.unobserve(element);
		element.classList.remove('sg-in');
		element.getBoundingClientRect();
		var replayApplied = false;
		var applyIn = function () {
			if (replayApplied) return;
			replayApplied = true;
			element.classList.add('sg-in');
		};
		window.requestAnimationFrame(function () {
			window.requestAnimationFrame(applyIn);
		});
		// rAF is throttled to a standstill in hidden/backgrounded frames — the
		// timeout guarantees the element can never be left stuck hidden.
		window.setTimeout(applyIn, 150);
	}
	function sgScan(root) {
		var scope = root && root.nodeType === 1 ? root : document;
		if (scope.nodeType === 1 && scope.hasAttribute && (scope.hasAttribute('data-sg-reveal') || scope.hasAttribute('data-sg-hover') || scope.hasAttribute('data-sg-loop'))) {
			sgProcess(scope);
		}
		var elements = scope.querySelectorAll('[data-sg-reveal]');
		for (var i = 0; i < elements.length; i += 1) sgProcess(elements[i]);
	}
	document.documentElement.classList.add('sg-motion');
	sgScan(document);
	try {
		var sgMutations = new MutationObserver(function (records) {
			records.forEach(function (record) {
				if (record.type === 'attributes') {
					sgProcess(record.target);
					return;
				}
				for (var n = 0; n < record.addedNodes.length; n += 1) {
					var node = record.addedNodes[n];
					if (node.nodeType === 1) sgScan(node);
				}
			});
		});
		sgMutations.observe(document.documentElement, {
			childList: true,
			subtree: true,
			attributes: true,
			attributeFilter: ['data-sg-reveal', 'data-sg-hover', 'data-sg-loop', 'data-sg-delay', 'data-sg-duration'],
		});
	} catch (e) {}
	document.addEventListener('pointerdown', function (event) {
		var target = event.target;
		if (!target || typeof target.closest !== 'function') return;
		var button = target.closest('[data-sg-hover="btn-ripple"]');
		if (!button) return;
		var rect = button.getBoundingClientRect();
		button.style.setProperty('--sg-x', (event.clientX - rect.left) + 'px');
		button.style.setProperty('--sg-y', (event.clientY - rect.top) + 'px');
		button.classList.remove('sg-rippling');
		button.getBoundingClientRect();
		button.classList.add('sg-rippling');
		window.setTimeout(function () { button.classList.remove('sg-rippling'); }, 650);
	}, true);
	window.__sgAnimations = { process: sgProcess, refresh: sgScan, replay: sgReplay, splitModes: SG_SPLIT_MODES };
}
if (!window.__sgAiLabels) {
	window.__sgAiLabels = (function () {
		var ready = false;
		var MEDIA = /^(img|video|picture|canvas|iframe|svg|object|embed)$/i;
		var CSS = 'sg-ai-label{position:absolute;z-index:3;display:inline-block;box-sizing:border-box;max-width:calc(100% - 16px);margin:0;padding:2px 8px;border-radius:999px;background:rgba(17,17,17,.74);color:#fff;font:600 11px/1.45 system-ui,sans-serif;letter-spacing:.01em;text-align:left;text-transform:none;text-shadow:none;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;box-shadow:0 0 0 1px rgba(255,255,255,.28);pointer-events:none;}[data-sg-ai-label]>sg-ai-label{left:8px;bottom:8px;}';
		function style() {
			if (document.getElementById('sg-ai-label-style')) return;
			var sheet = document.createElement('style');
			sheet.id = 'sg-ai-label-style';
			sheet.textContent = CSS;
			(document.head || document.documentElement).appendChild(sheet);
		}
		function place(element, badge) {
			if (!badge || !badge.parentNode) return;
			var host = badge.parentNode;
			var left = element.offsetLeft;
			var top = element.offsetTop;
			var height = element.offsetHeight;
			if (typeof left !== 'number' || element.offsetParent !== host) {
				var box = element.getBoundingClientRect();
				var frame = host.getBoundingClientRect();
				left = box.left - frame.left - host.clientLeft + host.scrollLeft;
				top = box.top - frame.top - host.clientTop + host.scrollTop;
				height = box.height;
			}
			badge.style.left = (left + 8) + 'px';
			badge.style.top = (top + Math.max(0, height - badge.offsetHeight - 8)) + 'px';
		}
		function label(element) {
			if (!ready || !element || element.nodeType !== 1 || !element.getAttribute) return;
			var text = element.getAttribute('data-sg-ai-label');
			var badge = element.__sgAiBadge || null;
			if (!text) {
				if (badge) {
					if (badge.parentNode) badge.parentNode.removeChild(badge);
					element.__sgAiBadge = null;
				}
				return;
			}
			var media = MEDIA.test(element.tagName);
			var anchor = element;
			if (media && element.parentNode && /^picture$/i.test(element.parentNode.tagName || '')) anchor = element.parentNode;
			var host = media ? anchor.parentNode : element;
			if (!host || host.nodeType !== 1) return;
			if (!badge) {
				badge = document.createElement('sg-ai-label');
				element.__sgAiBadge = badge;
			}
			if (badge.textContent !== text) badge.textContent = text;
			// The alt text says it already: screen readers need not hear it twice.
			if ((element.getAttribute('alt') || '').indexOf(text) !== -1) badge.setAttribute('aria-hidden', 'true');
			else badge.removeAttribute('aria-hidden');
			style();
			try {
				if (window.getComputedStyle(host).position === 'static') host.style.position = 'relative';
			} catch (e) {}
			if (!media) {
				if (badge.parentNode !== element) element.appendChild(badge);
				return;
			}
			if (badge.parentNode !== host || badge.previousSibling !== anchor) host.insertBefore(badge, anchor.nextSibling);
			place(element, badge);
			if (!element.__sgAiSized && typeof ResizeObserver !== 'undefined') {
				element.__sgAiSized = true;
				try {
					var sized = new ResizeObserver(function () { place(element, element.__sgAiBadge); });
					sized.observe(element);
					sized.observe(host);
				} catch (e) {}
			}
		}
		// A labelled element that left the page takes its badge along.
		function unlabel(node) {
			if (!node || node.nodeType !== 1 || node.isConnected) return;
			var badge = node.__sgAiBadge;
			if (!badge) return;
			if (badge.parentNode && badge.parentNode !== node) badge.parentNode.removeChild(badge);
			node.__sgAiBadge = null;
		}
		function scan(root) {
			if (!ready) return;
			var scope = root && root.nodeType === 1 ? root : document;
			if (scope.nodeType === 1 && scope.hasAttribute('data-sg-ai-label')) label(scope);
			var labelled = scope.querySelectorAll('[data-sg-ai-label]');
			for (var i = 0; i < labelled.length; i += 1) label(labelled[i]);
		}
		function start() {
			if (ready) return;
			ready = true;
			scan(document);
			if (typeof MutationObserver === 'undefined') return;
			try {
				new MutationObserver(function (records) {
					for (var r = 0; r < records.length; r += 1) {
						var record = records[r];
						if (record.type === 'attributes') {
							label(record.target);
							continue;
						}
						for (var d = 0; d < record.removedNodes.length; d += 1) unlabel(record.removedNodes[d]);
						for (var a = 0; a < record.addedNodes.length; a += 1) {
							var node = record.addedNodes[a];
							if (node.nodeType === 1 && !/^sg-ai-label$/i.test(node.tagName)) scan(node);
						}
					}
				}).observe(document.documentElement, { childList: true, subtree: true, attributes: true, attributeFilter: ['data-sg-ai-label', 'alt'] });
			} catch (e) {}
		}
		if (document.readyState === 'complete') window.setTimeout(start, 0);
		else window.addEventListener('load', function () { window.setTimeout(start, 0); });
		return { scan: scan };
	})();
}
}
